#!/bin/python3

import os
import sys

#
# Complete the getTotalX function below.
#
def getTotalX(a, b):
    l=list()
    for i in range(max(a),min(b)+1):
        count=0
        for j in a:
            if i%j==0:
                count+=1
        if count==len(a):
            l.append(i)
    final_count=0
    for i in l:
        count=0
        for j in b:
            
            if j%i==0:
                print(i,j)
                count+=1
        print(final_count)
        if count==len(b):
            final_count+=1
    return final_count


if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    total = getTotalX(a, b)

    f.write(str(total) + '\n')

    f.close()
