#!/bin/python3

import math
import os
import random
import re
import sys


if __name__ == '__main__':
    nd = input().split()

    n = int(nd[0])

    d = int(nd[1])

    a = list(map(int, input().rstrip().split()))
    
    temp=a[0:d]
    temp1=a[d:]
    for i in range(len(temp1)):
        print(temp1[i],end=" ")
    for i in range(len(temp)):
        print(temp[i],end=" ")
#77 97 58 1 86 58 26 10 86 51 41 73 89 7 10 1 59 58 84 77
